apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-k8s-app
  template:
    metadata:
      labels:
        app: aws-k8s-app
    spec:
      containers:
        - name: aws-k8s-app
          image: 518286664249.dkr.ecr.us-east-1.amazonaws.com/dockerfile:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
